Younlee
anjaemin/a_closing_expert pull request #11
Opened 2020-12-22 08:29 UTC by younlee1014

문자열 계산기 1차

2020-12-22 08:41 UTC, anjaemin commented on src/test/java/Calculator/CalculatorTest.java
> +}
입력값이 null 이거나 유효하지 않은 값일때의 테스트 케이스가 빠져있네여 Calculator.md 의 기능분리 부분 설명을 참조해서 테스트 케이스를 추가해보세여

2020-12-22 08:44 UTC, anjaemin commented on src/main/java/Calculator/CalculatorMain.java
> +
기능 요구사항을 보시면 숫자와 연산기호를 따로입력받는게 아닌 "2 * 3 + 2 / 4" 이런식의 입력을 한번에 받아서 기능을 구현하라고 되어있어여 확인해서 수정해주세여

2020-12-22 08:46 UTC, anjaemin requested changes
comment 참고해서 수정해보세여

2020-12-28 04:41 UTC, anjaemin commented on src/main/java/Calculator/Calculator.java
> +        if (input.equals(" ") || input == null) {
값을 하드코딩하지 마라...
빈값문자열(" ")도 문자열이니 상수(static final)로 해야 하지 않을까여?

2020-12-28 04:42 UTC, anjaemin commented on src/main/java/Calculator/Calculator.java
> +        return input.split(" ");
값을 하드코딩하지 마라...
위와 같습니다

2020-12-28 04:45 UTC, anjaemin commented on src/test/java/Calculator/CalculatorTest.java
> +        Calculator.makeResult("2 + 3 * 4 / 2");
makeResult 의 결과값을 검증하는 부분이 빠진거같네여

2020-12-28 04:52 UTC, anjaemin commented on src/test/java/Calculator/CalculatorTest.java
> +        assertThatExceptionOfType(IllegalArgumentException.class).isThrownBy(() -> Calculator.isBlank(input));
입력값이 "*" 가 들어오면 테스트가 실패되는데 맞는건가여?

2020-12-28 04:52 UTC, anjaemin commented on src/test/java/Calculator/CalculatorTest.java
> +        assertThatExceptionOfType(IllegalArgumentException.class).isThrownBy(() -> Calculator.calculate(2, operator, 5));
입력값이 "$"  가 들어오면 테스트 실패되는데 맞는건가여?

2020-12-28 04:56 UTC, anjaemin reviewed
피드백이 많지는 않아서 수정하고 다음단계로 진행되면 될것같네여
연산에 대한 로직은.... 저도 처음에 저렇게 했었는데 좀더 간편한걸 찾았어여
필요하면 설명해줄께여

2020-12-28 04:56 UTC, younlee1014 commented on src/test/java/Calculator/CalculatorTest.java
> +        assertThatExceptionOfType(IllegalArgumentException.class).isThrownBy(() -> Calculator.calculate(2, operator, 5));
사칙연산의 문구가 아니기 때문에 실패가 맞지 않나요??

2020-12-28 04:57 UTC, younlee1014 commented on src/test/java/Calculator/CalculatorTest.java
> +        assertThatExceptionOfType(IllegalArgumentException.class).isThrownBy(() -> Calculator.isBlank(input));
공백과 널에 대한 테스트 이기 때문에 문구가 들어오면 실패가 되어야 하는거 아닌가요?

2020-12-28 04:59 UTC, anjaemin commented on src/test/java/Calculator/CalculatorTest.java
> +        assertThatExceptionOfType(IllegalArgumentException.class).isThrownBy(() -> Calculator.isBlank(input));
공백과 널에 대한 테스트만 하면 되는데 정상적인 문구가 들어오는 테스트까지 들어갈 필요가 있을까여?
결정적으로 테스트가 통과가 안돼잖아여;;;

2020-12-28 05:00 UTC, anjaemin commented on src/test/java/Calculator/CalculatorTest.java
> +        assertThatExceptionOfType(IllegalArgumentException.class).isThrownBy(() -> Calculator.calculate(2, operator, 5));
사칙연산 문구에 대한 테스트만 진행하고 다른 문자열에 대해서는 테스트케이스가 분리되어야 할것 같네여

2020-12-28 05:00 UTC, younlee1014 commented
> 피드백이 많지는 않아서 수정하고 다음단계로 진행되면 될것같네여
> 연산에 대한 로직은.... 저도 처음에 저렇게 했었는데 좀더 간편한걸 찾았어여
> 필요하면 설명해줄께여

네 설명 부탁드립니다 :)

2020-12-28 05:01 UTC, younlee1014 commented on src/test/java/Calculator/CalculatorTest.java
> +        assertThatExceptionOfType(IllegalArgumentException.class).isThrownBy(() -> Calculator.calculate(2, operator, 5));
아~~ 넵넵!!

2020-12-28 05:01 UTC, younlee1014 commented on src/test/java/Calculator/CalculatorTest.java
> +        assertThatExceptionOfType(IllegalArgumentException.class).isThrownBy(() -> Calculator.isBlank(input));
아.. 안되는 부분까지 테스트 해야 하는줄 알았어요;;

2020-12-28 05:05 UTC, anjaemin commented
https://woowabros.github.io/tools/2017/07/10/java-enum-uses.html
이전에 양과장님이 올렸던 소스가 enum을 사용해서 만드셨던걸로 기억하는데 위 링크에서 저도 본적이 있었네여;;;
위 페이지 일단 읽어보세여 중간에 CalculatorType 이라는 enum 사용하는걸로 수정한 부분 이에여

2020-12-28 05:06 UTC, anjaemin commented on src/test/java/Calculator/CalculatorTest.java
> +        assertThatExceptionOfType(IllegalArgumentException.class).isThrownBy(() -> Calculator.isBlank(input));
안되는 부분은 안되는 테스트케이스를 별도로 작성해야져^^

2020-12-28 05:08 UTC, anjaemin commented on src/main/java/Calculator/Calculator.java
> +        if (input.equals(" ") || input == null) {
값을 하드코딩하지 마라.
상수(static final)를 만들고 이름을 부여해 이 변수의 역할이 무엇인지 의도를 드러내라.
구글에서 "java 상수"와 같은 키워드로 검색해 상수 구현 방법을 학습하고 적용해 본다.

박재성 아저씨한테 리뷰받을때 제가 받았던 코멘트네여;;; 참고하세여;;;

2020-12-28 05:11 UTC, anjaemin commented on src/test/java/Calculator/CalculatorTest.java
> +        assertThatExceptionOfType(IllegalArgumentException.class).isThrownBy(() -> Calculator.calculate(2, operator, 5));
아이고 죄송해여 제가 반대로 봤네여 사칙연산기호가 아닌 문자열이 들어왔을 경우에 대한 테스트져?;;;
"*" 문자열이 들어왔을때 테스트가 실패하겠네여;;;

2020-12-29 02:55 UTC, merged